###

POST  http://localhost:8000/api/register
Content-Type: application/json

{
    "username": "Shannia lee",
    "email":"rhea0951@gmail.com",
    "password": "test123",
    "password_confirmation": "test123"
}

#####

POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email" : "rhea0951@gmail.com",
    "password" : "test123"
}


####

POST http://localhost:8000/api/send/resetpassword
# Authorization: Bearer 2|BW7YMI8WzhkfNrXhvphouzG6cURmf5vimPKt1QA9
Content-Type: application/json

{
    "email" : "rhea0951@gmail.com"
}

#####

POST http://localhost:8000/api/questions/add
Authorization: Bearer 1|roO6r6iYlN3NUNmreg13Eyro2rcLgCEcFAtzXPRj

####

POST http://localhost:8000/api/questionnaire/create
Content-Type: application/json
Authorization: Bearer 1|yOo9S2hYRn7Uata0I7PawAlDZBmrGs9KdLeabPaI

{
    "title" : "test",
    "course": "logic",
    "time_duration": 40,
    "passing_score": 10,
    "easy_questions": 5,
    "average_questions": 5,
    "hard_questions":5,
    "total_questions": 15
}

###
GET http://localhost:8000/api/questionnaire/1
Authorization: Bearer 1|yOo9S2hYRn7Uata0I7PawAlDZBmrGs9KdLeabPaI


####
GET  http://localhost:8000/api/questionnaire/time/1
Authorization: Bearer 1|yOo9S2hYRn7Uata0I7PawAlDZBmrGs9KdLeabPaI


