###

POST  http://localhost:8000/api/register
Content-Type: application/json

{
    "username": "Shannia lee",
    "email":"rhea.ardiente@mlhuillier.com",
    "password": "test123",
    "password_confirmation": "test123"
}

#####

POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email" : "rhea.ardiente@mlhuillier.com",
    "password" : "test123"
}

####
POST http://localhost:8000/api/logout
Authorization: Bearer 1|roO6r6iYlN3NUNmreg13Eyro2rcLgCEcFAtzXPRj

####

POST http://localhost:8000/api/send/resetpassword
# Authorization: Bearer 2|BW7YMI8WzhkfNrXhvphouzG6cURmf5vimPKt1QA9
Content-Type: application/json

{
    "email" : "rhea.ardiente@mlhuillier.com"
}

#####

POST http://localhost:8000/api/questions/add
Authorization: Bearer 1|roO6r6iYlN3NUNmreg13Eyro2rcLgCEcFAtzXPRj

####

POST http://localhost:8000/api/questionnaire/create
Content-Type: application/json
Authorization: Bearer 1|g0pSPbBHXVRCyxKCzuU04QCMl5rFb9rUm8bAvVkl

{
    "title" : "test",
    "course": "logic",
    "time_duration": 40,
    "passing_score": 10,
    "easy_questions": 5,
    "average_questions": 5,
    "hard_questions":5,
    "total_questions": 15
}

###
GET http://localhost:8000/api/questionnaire/1
Authorization: Bearer 1|g0pSPbBHXVRCyxKCzuU04QCMl5rFb9rUm8bAvVkl


####
GET  http://localhost:8000/api/questionnaire/time/1
Authorization: Bearer 1|kxETdJyycr0Tef9JiomNqN5cszPlBxRDDMRZCQao

####

####
POST http://localhost:8000/api/checkanswer
Content-Type: application/json
Authorization: Bearer 1|g0pSPbBHXVRCyxKCzuU04QCMl5rFb9rUm8bAvVkl

{
    "id" : 1,
    "answers" : "[{'6':'C'},{'56':'B'},{'95':'D'},{'74':'D'},{'106':'C'},{'75':'C'},{'142':'D'},{'127':'B'},{'123':'A'},{'57':'A'},{'53':'A'},{'118':'D'},{'132':'C'},{'88':'C'},{'97':'D'}]"
}
