###

POST  http://localhost:8000/api/register
Content-Type: application/json

{
    "username": "Shannia lee",
    "email":"rhea.ardiente@mlhuillier.com",
    "password": "test123",
    "password_confirmation": "test123"
}

#####

POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email" : "rhea.ardiente@mlhuillier.com",
    "password" : "test123"
}

####
POST http://localhost:8000/api/logout
Authorization: Bearer 1|roO6r6iYlN3NUNmreg13Eyro2rcLgCEcFAtzXPRj

####

POST http://localhost:8000/api/send/resetpassword
# Authorization: Bearer 2|BW7YMI8WzhkfNrXhvphouzG6cURmf5vimPKt1QA9
Content-Type: application/json

{
    "email" : "rhea.ardiente@mlhuillier.com"
}

#####

POST http://localhost:8000/api/questions/add
Authorization: Bearer 1|roO6r6iYlN3NUNmreg13Eyro2rcLgCEcFAtzXPRj

####

POST http://localhost:8000/api/questionnaire/create
Content-Type: application/json
Authorization: Bearer 21|QQex4DIJ8imyI46Tr15aKQ3TZ4JjMuKEuZOhRdTX

{
    "title" : "test2",
    "course": "logic",
    "time_duration": 40,
    "passing_score": 10,
    "easy_questions": 5,
    "average_questions": 5,
    "hard_questions":5,
    "total_questions": 15
}

###
GET http://localhost:8000/api/questionnaire/3
Authorization: Bearer 21|QQex4DIJ8imyI46Tr15aKQ3TZ4JjMuKEuZOhRdTX


####
GET  http://localhost:8000/api/questionnaire/time/1
Authorization: Bearer 21|QQex4DIJ8imyI46Tr15aKQ3TZ4JjMuKEuZOhRdTX

####

####
POST http://localhost:8000/api/checkanswer
Content-Type: application/json
Authorization: Bearer 21|QQex4DIJ8imyI46Tr15aKQ3TZ4JjMuKEuZOhRdTX

{
    "id" : 1,
    "answers" : "[{'69':'A'},{'39':'B'},{'94':'A'},{'85':'A'},{'217':'C'},{'203':'C'},{'284':'C'},{'10':'A'},{'16':'B'},{'87':'C'},{'3':'D'},{'271':'C'},{'124':'C'},{'61':'A'},{'157':'D'}]"
}

######

GET http://localhost:8000/api/result
Content-Type: application/json
Authorization: Bearer 21|QQex4DIJ8imyI46Tr15aKQ3TZ4JjMuKEuZOhRdTX
