// export const ACTION_SET_REPORTS = 'reports/ACTION_SET_REPORTS'
export const ACTION_ADD_QUESTION = 'addQuestion/ACTION_ADD_QUESTION'

export const MUTATION_ADD_QUESTION = 'addQuestion/ACTION_ADD_QUESTION'
// export const MUTATION_DELETE_REPORT = 'reports/MUTATION_DELETE_REPORT'
// export const MUTATION_UPDATE_REPORT = 'reports/MUTATION_UPDATE_REPORT'

export const GETTER_QUESTION = 'addQuestion/GETTER_QUESTION'