// export const ACTION_SET_REPORTS = 'reports/ACTION_SET_REPORTS'
export const ACTION_SET_QUESTIONS = 'getAllQuestions/ACTION_SET_QUESTIONS'
export const ACTION_ADD_QUESTION = 'addQuestion/ACTION_ADD_QUESTION'
export const ACTION_DELETE_QUESTION = 'addQuestion/ACTION_DELETE_QUESTION'
export const ACTION_UPDATE_QUESTION = 'addQuestion/ACTION_UPDATE_QUESTION'

export const MUTATION_SET_QUESTIONS = 'getAllQuestions/MUTATION_SET_QUESTIONS'
export const MUTATION_ADD_QUESTION = 'addQuestion/MUTATION_ADD_QUESTION'
export const MUTATION_DELETE_REPORT = 'addQuestion/MUTATION_DELETE_REPORT'
export const MUTATION_UPDATE_REPORT = 'addQuestion/MUTATION_UPDATE_REPORT'

export const GETTER_QUESTION = 'addQuestion/GETTER_QUESTION'
