export const ACTION_SET_LOGIN = 'users/ACTION_SET_LOGIN'
export const MUTATION_SET_LOGIN = 'users/MUTATION_SET_LOGIN'

export const GETTER_LOGIN = 'users/GETTER_USER'
export const GETTER_USERS = 'users/GETTER_USERS'

export const ACTION_SET_REGISTER = 'users/ACTION_SET_REGISTER'
export const MUTATION_SET_REGISTER = 'users/MUTATION_SET_REGISTER'
